apiVersion: operator.kelson.com/v1alpha1
kind: TestRunner
metadata:
  labels:
    app.kubernetes.io/name: testrunner
    app.kubernetes.io/instance: testrunner-sample
    app.kubernetes.io/part-of: tester-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: tester-operator
  name: testrunner-sample
spec:
  # TODO(user): Add fields here
